# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-17 20:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('mon_start', models.IntegerField(blank=True, default=9, null=True)),
                ('mon_end', models.IntegerField(blank=True, default=17, null=True)),
                ('tue_start', models.IntegerField(blank=True, default=9, null=True)),
                ('tue_end', models.IntegerField(blank=True, default=17, null=True)),
                ('wed_start', models.IntegerField(blank=True, default=9, null=True)),
                ('wed_end', models.IntegerField(blank=True, default=17, null=True)),
                ('thu_start', models.IntegerField(blank=True, default=9, null=True)),
                ('thu_end', models.IntegerField(blank=True, default=17, null=True)),
                ('fri_start', models.IntegerField(blank=True, default=9, null=True)),
                ('fri_end', models.IntegerField(blank=True, default=17, null=True)),
                ('preferred_hours', models.IntegerField()),
                ('max_shift', models.IntegerField(default=8)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledEmployee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.IntegerField()),
                ('end_time', models.IntegerField()),
                ('day', models.CharField(default='Monday', max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Employee')),
            ],
        ),
    ]
