# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-17 20:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(default='Monday', max_length=10)),
                ('start_time', models.IntegerField(default=9)),
                ('end_time', models.IntegerField(default=13)),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduledemployee',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
        migrations.DeleteModel(
            name='ScheduledEmployee',
        ),
    ]
