# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-17 21:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170817_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledWorker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Shift')),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('shift_availability', models.CharField(default='', max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='scheduledworker',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Worker'),
        ),
    ]
