# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-17 21:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20170817_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='preferred_hours',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
