# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-18 01:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_worker_preferred_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='shift_availability',
        ),
        migrations.AddField(
            model_name='worker',
            name='shift_availability',
            field=models.ManyToManyField(to='core.Shift'),
        ),
    ]
