# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-18 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20170817_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='full_time_shift',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='part_time_workers',
            field=models.IntegerField(default=1),
        ),
    ]
